### ISSUE TITLE
Hover issue

### ISSUE THREAD

**Issue by sir-hashpipe** [urre/avanza-night-mode#1]
The small box showing the value when hovering over the graph does not work. It's all black unfortunately.
And the font is wrong but no biggie:
![ava1](https://user-images.githubusercontent.com/35771705/166927641-ae3a09c6-ce84-46af-a280-a151a6e1d74d.png)
![ava2](https://user-images.githubusercontent.com/35771705/166927652-aa71f5e8-40a3-4481-8bcf-c7dd3ddf47d5.png)
)

**Comment by urre** [comment]
ah, i'll look at that

**Comment by urre** [comment]
![CleanShot 2022-05-08 at 13 16 47@2x](https://user-images.githubusercontent.com/307676/167293738-77eb9b87-205a-4af2-9088-eb3040655882.jpg)

this is fixed now @sir-hashpipe

**Comment by sir-hashpipe** [comment]
Amazing will check asap! Tackar ödmjukast!

**Comment by sir-hashpipe** [comment]
The fix seems to have introduced another issue not present in previous version:)
![avafel](https://user-images.githubusercontent.com/35771705/167398058-d289fbd6-6cc7-4635-90dd-6f76dfc5ff20.png)

**Comment by urre** [comment]
@sir-hashpipe Cool! Made a new update today also!
