### ISSUE TITLE
New issue from update

### ISSUE THREAD

**Issue by sir-hashpipe** [urre/avanza-night-mode#2]
There seems to be a new issue introduced in previous fix:)
![avafel](https://user-images.githubusercontent.com/35771705/167665897-ed93dfa2-1c95-4907-b78a-6ad6e36f6c93.png)

And also this but might not matter? Was there before as well.
![avafel2](https://user-images.githubusercontent.com/35771705/167665978-c5ab57d1-4f57-4f9a-9a33-a283aa08c3c6.png)

**Comment by urre** [comment]
oh, couple of more things to look at

**Comment by urre** [comment]
Updated now!

**Comment by sir-hashpipe** [comment]
Great thanks!
