### ISSUE TITLE
More issues

### ISSUE THREAD

**Issue by sir-hashpipe** [urre/avanza-night-mode#3]
Hi,

Found some more issues...
Don't know how much time and effort you wanna give this project. If you are busy just say and I won't file any more issues:)
The plugin works for most daily tasks anyway.

![ava1](https://user-images.githubusercontent.com/35771705/168835805-dbcb2f9f-c7e2-4e89-a864-934fcd051875.png)
![ava2](https://user-images.githubusercontent.com/35771705/168835812-02b19a31-652d-42f3-bd28-951fa2f48e44.png)
![ava3](https://user-images.githubusercontent.com/35771705/168835814-b3acd835-4b65-4fe3-ad30-d6a721f55c37.png)
![ava4](https://user-images.githubusercontent.com/35771705/168835818-484b0a02-a47b-403f-8efb-868d70fcd5ad.png)

**Comment by urre** [comment]
Just made a couple of more updates @sir-hashpipe!

**Comment by sir-hashpipe** [comment]
Thanks! Börsskärm is working much better now.

**Comment by urre** [comment]
great!
